In [1]:
import collections
from inputplotdataISM import inputplotdict
plotlist = [
'figrhopthgrid_m12',\
    \
#'figintrhogfrompardist_m12mhr0_5kpcr0_9_usekez',\
#    'figintrhogfrompardist_m11g0_5kpcr0_9_usekez',\
#    'gpm12mcr_700HI10'
           ]
for plotneed in plotlist:
    inputplotdict[plotneed]['_plotfunction'](inputplotdict[plotneed])

/home/tkc004/samsonprogram/tools/crgridfunction.py:80: SyntaxWarning: import * only allowed at module level
  def crgridfunction(gridag,runtodo,wanted,idir,plotupt,plotit,startno,Nsnap,snapsep,cbcolor='hot',


wanted rhoPth
dirneed ['m12imhdcvhr', 'm12fmhdcvhr', 'm12mmhdcvhr', 'm12icr_700hr', 'm12fcr_700hr', 'm12mcr_700hr']
extendedrange 0
addtitleinbox 1
nrows, ncols 2 3
rundir /m12i_mass7000_MHDCR_tkFIX/mhdcv/
rundir /m12i_mass7000_MHDCR_tkFIX/mhdcv/
the_snapdir /home/tkc004//oasis/philruns///m12i_mass7000_MHDCR_tkFIX/mhdcv///output/
Nsnapstring 600
loading file : /home/tkc004//oasis/philruns///m12i_mass7000_MHDCR_tkFIX/mhdcv///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [15557681 23025661  1676566        0  3386732        0]
npart_total: [55633181 70514272  5513331        0 15355656        0]
flag_cooling 1
this time 1.0
hubble 0.702
atime 1.0
loading file : /home/tkc004//oasis/philruns///m12i_mass7000_MHDCR_tkFIX/mhdcv///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [15557681 23025661  1676566        0  3386732        0]
npart_total: [55633181 70514272  5513331        0 15355656        0]
flag_cooling 1
xvcen, yvcen, zvcen -48.68 71.9 95.28
Gvx,Gvy,Gvz -8.724718888117273 

/home/tkc004/samsonprogram/tools/crgridfunction.py:297: RuntimeWarning: divide by zero encountered in log10
  im = gridag[idir].contourf(xedges[:-1], yedges[:-1], np.log10(Hadd),\
/home/tkc004/oasis/yt/yt-conda/lib/python2.7/site-packages/matplotlib/contour.py:1004: UserWarning: The following kwargs were not used by contour: 'aspect'
  s)


 [3998535 5277691  476460       0 1088254       0]
npart_total: [64073597 81363848  7086235        0 17885838        0]
flag_cooling 1
this time 1.0
hubble 0.702
atime 1.0
loading file : /home/tkc004//oasis/philruns///m12f_mass7000/mhdcv///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [3998535 5277691  476460       0 1088254       0]
npart_total: [64073597 81363848  7086235        0 17885838        0]
flag_cooling 1
xvcen, yvcen, zvcen -149.65 161.86 109.65
Gvx,Gvy,Gvz 6.788665387892974 -1.767523056166311 -4.082557980956234
H [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
np.sum(Hadd) 0.9997816368313269
xedges [-3.5  -3.35 -3.2  -3.05 -2.9  -2.75 -2.6  -2.45 -2.3  -2.15 -2.   -1.85
 -1.7  -1.55 -1.4  -1.25 -1.1  -0.95 -0.8  -0.65 -0.5  -0.35 -0.2  -0.05
  0.1   0.25  0.4   0.55  0.7   0.85  1.    1.15  1.3   1.45  1.6   1.75
  1.9   2.05  2.2   2.35  2.5   2.65  2.8   2.9

/home/tkc004/oasis/yt/yt-conda/lib/python2.7/site-packages/matplotlib/figure.py:2299: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "
