In [75]:
from stdmodandoption import *

wanted='nsrad'
dirneed = ['m12mcr_700hr']
the_prefix = 'snapshot'
the_suffix = '.hdf5'


if wanted=='sfrrad' or wanted=='nsrad' or wanted == 'cumnsmrad':
    withinr = 15.
    minr = 0.5
    maxlength=0.25
    usecen=0
    normalized=1
    usenscen=1
    usesphrad=1
    uselog=1
    Myrneed=600
    ageneed=200 #Myr
    radlist = np.linspace(minr, withinr,10)
    for runtodo in dirneed:
        info=SSF.outdirname(runtodo, Myrneed)
        rundir=info['rundir']
        runtitle=info['runtitle']
        slabel=info['slabel']
        snlabel=info['snlabel']
        dclabel=info['dclabel']
        resolabel=info['resolabel']
        the_snapdir=info['the_snapdir']
        Nsnapstring=info['Nsnapstring']
        havecr=info['havecr']
        haveB=info['haveB']
        Fcal=info['Fcal']
        iavesfr=info['iavesfr']
        timestep=info['timestep']
        color=info['color']
        h0=info['h0']
        cosmo=info['cosmo']
        usepep=info['usepep']
        maindir=info['maindir']
        snumadd=info['snumadd']
        halostr=info['halostr']
        rotface = 1
        loccen = 1
        S = SSF.readsnapwcen(the_snapdir, Nsnapstring, 4, snapshot_name=the_prefix, extension=the_suffix,\
         havecr=havecr,h0=h0,cosmo=cosmo, usepep=usepep, maindir=maindir,snumadd=snumadd,rotface=rotface,\
         loccen=loccen,runtodo=runtodo,rundir=rundir,halostr=halostr)
        Sage = S['age']
        Spos = S['p']
        Sx = Spos[:,0]
        Sy = Spos[:,1]
        Sz = Spos[:,2]
        Sm = S['m']
        agecutlow = np.amax(Sage)-0.001*ageneed
        agecuthigh = np.amax(Sage)
        cuta = (Sage> agecutlow) & (Sage <agecuthigh)
        Sx=Sx[cuta]; Sy=Sy[cuta]; Sz=Sz[cuta]; Sm=Sm[cuta];
        G = SSF.readsnapwcen(the_snapdir, Nsnapstring, 0, snapshot_name=the_prefix, extension=the_suffix,\
         havecr=havecr,h0=h0,cosmo=cosmo, usepep=usepep, maindir=maindir,snumadd=snumadd,rotface=rotface,\
         loccen=loccen,runtodo=runtodo,rundir=rundir,halostr=halostr)

rundir /m12m_mass7000/cr_700/
loading file : /home/tkc004//oasis/philruns///m12m_mass7000/cr_700///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [8530666 9355240  399118       0  550035       0]
npart_total: [132832344 140876456  10063684         0   8072148         0]
flag_cooling 1
this time 1.0
hubble 0.702
atime 1.0
loading file : /home/tkc004//oasis/philruns///m12m_mass7000/cr_700///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [8530666 9355240  399118       0  550035       0]
npart_total: [132832344 140876456  10063684         0   8072148         0]
flag_cooling 1
xvcen, yvcen, zvcen -185.72 -9.18 142.11
rundir /m12m_mass7000/cr_700/
Gvx,Gvy,Gvz -1.9083296337102158 -9.575566226227846 -0.25201589906004906
loading file : /home/tkc004//oasis/philruns///m12m_mass7000/cr_700///output//snapdir_600/snapshot_600.0.hdf5
npart_file:  [8530666 9355240  399118       0  550035       0]
npart_total: [132832344 140876456  10063684         0   8072148         0]
flag_cooling 1
this

In [40]:
fhdf5 = h5py.File('/oasis/tscc/scratch/tkc004/snipshot/test4.hdf5', 'w')
ptype=0
grp0 = fhdf5.create_group("PartType"+str(ptype)+"/")
hdf5keyexceptions=['header']
write_layer(grp0, G,hdf5keyexceptions=hdf5keyexceptions)

k,v cregy [3.71512310e-07 3.54678115e-07 3.51120543e-07 ... 8.48772835e-04
 6.26823500e-04 4.85434231e-04]
k,v vcen [-185.72   -9.18  142.11]
k,v id [121415835 120051369 120050478 ...  33650731  33648751  38784233]
k,v nh [4.29768477e-07 3.60729302e-07 3.83916785e-07 ... 1.72155481e-07
 2.07648824e-07 2.19049809e-07]
k,v ne [1.16659403 1.16661143 1.16660678 ... 1.16664195 1.16663587 1.16663361]
k,v B [[-2.77000499e-14 -6.97796732e-14  1.12173219e-14]
 [ 4.24889960e-14 -4.83687919e-14 -4.84510695e-14]
 [-1.40339072e-14 -7.46857655e-14  2.20504928e-14]
 ...
 [ 3.11615257e-13 -4.28460976e-13 -1.13549869e-12]
 [-1.25653694e-12  4.90119148e-13 -2.75588092e-12]
 [-3.79072045e-12  1.63905889e-12 -1.96420586e-12]]
k,v angL [-55.43534008  -6.21232098 -31.10745513]
k,v cen [37545.64736109 41588.79229482 46768.92135951]
k,v sfr [0. 0. 0. ... 0. 0. 0.]
k,v rho [1.23982279e-09 1.13905248e-09 1.18563842e-09 ... 8.27163584e-10
 9.00795473e-10 9.15148407e-10]
k,v h [16.32122708 16.74681036 16.51917564

In [69]:
fhdf5.close()
del fhdf5

NameError: name 'fhdf5' is not defined

In [67]:
def write_layer(gp, adict,hdf5keyexceptions=[]):
    for k,v in adict.items():
        if k not in hdf5keyexceptions:
            if isinstance(v, dict):
                gp1 = gp.create_group(k)
                write_layer(gp1, v)
            else:
                print 'k,v', k,v
                gp.create_dataset(k, data=np.atleast_1d(v))

In [42]:
fhdf5 = h5py.File('/oasis/tscc/scratch/tkc004/snipshot/test4.hdf5', 'r')

In [43]:
fhdf5

<HDF5 file "test4.hdf5" (mode r)>

In [46]:
for name in fhdf5:
    print name

PartType0


In [55]:
Gnew=dict()
for groupname in fhdf5:
    fgroup = fhdf5[groupname]
    for name in fgroup:
        Gnew[name] = fgroup[name][:]

In [65]:
def savesnipshot(parlist,fname,ptypelist = [0]):
    hdf5keyexceptions=['header']
    fhdf5 = h5py.File(fname, 'w')
    for ptype,pdata in zip(ptypelist,parlist):
        grp = fhdf5.create_group("PartType"+str(ptype)+"/")
        write_layer(grp, pdata,hdf5keyexceptions=hdf5keyexceptions)
    fhdf5.close()
    del fhdf5
    return None

In [5]:
parlist=[G,S]
fname = '/oasis/tscc/scratch/tkc004/snipshot/test4.hdf5'
savesnipshot(parlist,fname,ptypelist = [0,4])

k,v cregy [3.71512310e-07 3.54678115e-07 3.51120543e-07 ... 8.48772835e-04
 6.26823500e-04 4.85434231e-04]
k,v vcen [-185.72   -9.18  142.11]
k,v id [121415835 120051369 120050478 ...  33650731  33648751  38784233]
k,v nh [4.29768477e-07 3.60729302e-07 3.83916785e-07 ... 1.72155481e-07
 2.07648824e-07 2.19049809e-07]
k,v ne [1.16659403 1.16661143 1.16660678 ... 1.16664195 1.16663587 1.16663361]
k,v B [[-2.77000499e-14 -6.97796732e-14  1.12173219e-14]
 [ 4.24889960e-14 -4.83687919e-14 -4.84510695e-14]
 [-1.40339072e-14 -7.46857655e-14  2.20504928e-14]
 ...
 [ 3.11615257e-13 -4.28460976e-13 -1.13549869e-12]
 [-1.25653694e-12  4.90119148e-13 -2.75588092e-12]
 [-3.79072045e-12  1.63905889e-12 -1.96420586e-12]]
k,v angL [-55.43534008  -6.21232098 -31.10745513]
k,v cen [37545.64736109 41588.79229482 46768.92135951]
k,v sfr [0. 0. 0. ... 0. 0. 0.]
k,v rho [1.23982279e-09 1.13905248e-09 1.18563842e-09 ... 8.27163584e-10
 9.00795473e-10 9.15148407e-10]
k,v h [16.32122708 16.74681036 16.51917564

In [15]:
fname = '/oasis/tscc/scratch/tkc004/snipshot/test4.hdf5'
data = readsnipshot(fname,ptypelist = [0,4])

In [2]:
def readsnipshot(fname,ptypelist = [0]):
    fhdf5 = h5py.File(fname, 'r')
    parlist=[]
    bnamelist=[]
    for ptype in ptypelist:
        parlist.append(dict())
        bnamelist.append("PartType"+str(ptype)+"/")
    for i, bname in enumerate(bnamelist):
        fgroup = fhdf5[bname]
        for name in fgroup:
            parlist[i][name] = fgroup[name][:]
    fhdf5.close()
    del fhdf5
    return parlist

In [87]:
def Gspcut(G,spno=1):
    Gnew={}
    Gm = G['m']
    Glen = len(Gm)
    if spno>1:
        for key in G:
            Gshape = np.array(G[key]).shape
            if Gshape[0]<Glen-1:
                Gnew[key]=G[key]
            else:
                if len(Gshape)==1:
                    Gnew[key]=G[key][::spno]
                else:
                    Glist = []
                    for iy in range(Gshape[1]):
                        Gx = np.array(G[key][:,iy]);
                        Glist.append(Gx[::spno])
                    Gtri = np.vstack((Glist)).T    
                    Gnew[key]=Gtri
        Gnew['m']=spno*Gnew['m']
        return Gnew
    else:
        return G
        


def Gwithinrcut(Gn,withinr=-1):
    Gnew={}
    if withinr>0:
        Gp = Gn['p']; Gx = Gp[:,0]; Gy = Gp[:,1]; Gz = Gp[:,2];
        Glen = len(Gx)
        #consider only particles within withinr
        Gr = np.sqrt(Gx*Gx+Gy*Gy+Gz*Gz);
        cutr = Gr<withinr;
        for key in Gn:
            Gshape = np.array(Gn[key]).shape
            print 'key', key
            print 'np.array(Gn[key]).shape',np.array(Gn[key]).shape
            if len(Gshape)==0:
                Gnew[key]=Gn[key]
            elif Gshape[0]<Glen-1:
                Gnew[key]=Gn[key]
            else:
                if len(Gshape)==1:
                    Gnew[key]=Gn[key][cutr]
                else:
                    Glist = []
                    for iy in range(Gshape[1]):
                        Gx = np.array(Gn[key][:,iy]);
                        Glist.append(Gx[cutr])
                    Gtri = np.vstack((Glist)).T    
                    Gnew[key]=Gtri
        return Gnew
    else:
        return Gn

In [55]:
G = data[0]
Gdatacut = Gspcut(G,spno=10)

In [62]:
Gcutori = Gwithinrcut(G,withinr=100)

key cregy
np.array(Gn[key]).shape (132832344,)
key vcen
np.array(Gn[key]).shape (3,)
key id
np.array(Gn[key]).shape (132832344,)
key nh
np.array(Gn[key]).shape (132832344,)
key ne
np.array(Gn[key]).shape (132832344,)
key B
np.array(Gn[key]).shape (132832344, 3)
key angL
np.array(Gn[key]).shape (3,)
key cen
np.array(Gn[key]).shape (3,)
key sfr
np.array(Gn[key]).shape (132832344,)
key rho
np.array(Gn[key]).shape (132832344,)
key h
np.array(Gn[key]).shape (132832344,)
key k
np.array(Gn[key]).shape (1,)
key m
np.array(Gn[key]).shape (132832344,)
key cregyp
np.array(Gn[key]).shape (132832344,)
key p
np.array(Gn[key]).shape (132832344, 3)
key cregyl
np.array(Gn[key]).shape (132832344,)
key u
np.array(Gn[key]).shape (132832344,)
key v
np.array(Gn[key]).shape (132832344, 3)
key cregyg
np.array(Gn[key]).shape (132832344,)
key cregyd
np.array(Gn[key]).shape (132832344,)
key z
np.array(Gn[key]).shape (132832344, 15)
key cregya
np.array(Gn[key]).shape (132832344,)


In [56]:
Gcutr=Gwithinrcut(Gdatacut,withinr=100)

key cregy
np.array(Gn[key]).shape (13283235,)
key vcen
np.array(Gn[key]).shape (3,)
key id
np.array(Gn[key]).shape (13283235,)
key nh
np.array(Gn[key]).shape (13283235,)
key ne
np.array(Gn[key]).shape (13283235,)
key B
np.array(Gn[key]).shape (13283235, 3)
key angL
np.array(Gn[key]).shape (3,)
key cen
np.array(Gn[key]).shape (3,)
key sfr
np.array(Gn[key]).shape (13283235,)
key rho
np.array(Gn[key]).shape (13283235,)
key h
np.array(Gn[key]).shape (13283235,)
key k
np.array(Gn[key]).shape (1,)
key m
np.array(Gn[key]).shape (13283235,)
key cregyp
np.array(Gn[key]).shape (13283235,)
key p
np.array(Gn[key]).shape (13283235, 3)
key cregyl
np.array(Gn[key]).shape (13283235,)
key u
np.array(Gn[key]).shape (13283235,)
key v
np.array(Gn[key]).shape (13283235, 3)
key cregyg
np.array(Gn[key]).shape (13283235,)
key cregyd
np.array(Gn[key]).shape (13283235,)
key z
np.array(Gn[key]).shape (13283235, 15)
key cregya
np.array(Gn[key]).shape (13283235,)


In [57]:
len(Gdatacut['cregy'])

13283235

In [63]:
len(Gcutori['cregy'])

5159789

In [58]:
np.amax(Gcutr['p'][:,0])

99.53826711117149

In [61]:
Gcutr['vcen']

array([-185.72,   -9.18,  142.11])

In [64]:
np.array(G['p']).shape[0]

132832344

In [1]:
from stdmodandoption import *

In [70]:
savesnipshot([Gcutori],fname,ptypelist = [0])

k,v cregy [3.44545732e-02 2.20981886e-02 1.63689640e-02 ... 4.48185204e-05
 3.99766349e-05 2.11294068e-05]
k,v vcen [-185.72   -9.18  142.11]
k,v id [102550701  54040351  60493722 ... 128555758  94242918  52163649]
k,v nh [0.00196156 0.00630677 0.00645981 ... 0.99999994 1.         1.        ]
k,v ne [1.11092162e+00 1.09138298e+00 1.09054625e+00 ... 3.51671368e-08
 6.67267963e-10 3.00296843e-10]
k,v B [[ 5.96294385e-09  5.93258543e-08  2.99876851e-08]
 [-1.28859236e-08  1.42869211e-08  8.58729637e-11]
 [ 1.18433114e-07  4.94747241e-08 -9.04219786e-08]
 ...
 [ 2.37073593e-06  7.42847578e-07  1.91765296e-06]
 [ 4.84054569e-06  5.40813056e-08  3.47849800e-06]
 [ 1.73796618e-06 -1.04937857e-06  5.17087095e-06]]
k,v angL [-55.43534008  -6.21232098 -31.10745513]
k,v cen [37545.64736109 41588.79229482 46768.92135951]
k,v sfr [0. 0. 0. ... 0. 0. 0.]
k,v rho [2.86551089e-06 5.81846118e-06 6.83246359e-06 ... 3.19243593e-03
 7.27858210e-03 9.41382183e-03]
k,v h [1.26077222 1.04409057 0.93682734 ..

In [74]:
Scutori = Gwithinrcut(S,withinr=100)

NameError: name 'S' is not defined

In [82]:
def compresswithinr(parlist,ptypelist,withinr,fname):
    parGcutlist=[]
    for parG, ptype in zip(parlist,ptypelist):
        parGcut = Gwithinrcut(parG,withinr=100)
        parGcutlist.append(parGcut)
    savesnipshot(parGcutlist,fname,ptypelist = ptypelist)
    return None

In [88]:
parlist=[G,S]
ptypelist=[0,4]
withinr=100
fname = '/oasis/tscc/scratch/tkc004/snipshot/test4.hdf5'
compresswithinr(parlist,ptypelist,withinr,fname)

key cregy
np.array(Gn[key]).shape (132832344,)
key header
np.array(Gn[key]).shape (15,)
key vcen
np.array(Gn[key]).shape (3,)
key id
np.array(Gn[key]).shape (132832344,)
key nh
np.array(Gn[key]).shape (132832344,)
key ne
np.array(Gn[key]).shape (132832344,)
key B
np.array(Gn[key]).shape (132832344, 3)
key angL
np.array(Gn[key]).shape (3,)
key cen
np.array(Gn[key]).shape (3,)
key sfr
np.array(Gn[key]).shape (132832344,)
key rho
np.array(Gn[key]).shape (132832344,)
key h
np.array(Gn[key]).shape (132832344,)
key k
np.array(Gn[key]).shape ()
key m
np.array(Gn[key]).shape (132832344,)
key cregyp
np.array(Gn[key]).shape (132832344,)
key p
np.array(Gn[key]).shape (132832344, 3)
key cregyl
np.array(Gn[key]).shape (132832344,)
key u
np.array(Gn[key]).shape (132832344,)
key v
np.array(Gn[key]).shape (132832344, 3)
key cregyg
np.array(Gn[key]).shape (132832344,)
key cregyd
np.array(Gn[key]).shape (132832344,)
key z
np.array(Gn[key]).shape (132832344, 15)
key cregya
np.array(Gn[key]).shape (132832

In [86]:
print S

{'angL': array([-202.24262876,  -25.53922481, -117.30524809]), 'cen': array([37545.63052267, 41590.78908653, 46768.53613172]), 'header': [array([8530666, 9355240,  399118,       0,  550035,       0], dtype=int32), array([0., 0., 0., 0., 0., 0.]), 1.0, 0.0, 1, 1, array([132832344, 140876456,  10063684,         0,   8072148,         0],
      dtype=uint32), 1, 16, 60000.0, 0.272, 0.728, 0.702, 1, 15], 'vcen': array([-185.72,   -9.18,  142.11]), 'id': array([ 23891462,  11326533,  10955088, ..., 118249838, 118027243,
       109612284]), 'age': array([0.10542384, 0.09702651, 0.09697186, ..., 0.27619311, 0.27347478,
       0.28703329]), 'm': array([5.10129400e-07, 5.37892228e-07, 5.47786869e-07, ...,
       4.32890530e-07, 4.71825033e-07, 5.04015979e-07]), 'p': array([[ -867.47633371, -1846.36477686,   162.72840466],
       [ -971.45132399, -1792.43534351,    99.28860822],
       [ -970.82947316, -1790.56738888,    99.16599275],
       ...,
       [  -56.21548015,    48.29045898,    89.9705

In [89]:
data = readsnipshot(fname,ptypelist = [0,4])

In [92]:
Gnew=data[0]

In [93]:
Gnew['p']

array([[ 14.23788363,   2.03040429,  -5.07135507],
       [ 14.31929402,   2.11619183,  -4.42988045],
       [ 14.03442586,   2.48808125,  -4.28250557],
       ...,
       [  3.25425395, -21.41136318,  -0.45457192],
       [  3.22582364, -21.46403474,  -0.43619445],
       [  3.22126874, -21.47536005,  -0.41098941]])